// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsHuyenLC.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsHuyenLC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012153615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("numeric");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LichHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdLopHoc")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhongHoc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.ToTable("LichHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhongHoc")
                        .HasColumnType("text");

                    b.Property<int>("SiSoHienTai")
                        .HasColumnType("integer");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.PhanCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopHocId");

                    b.ToTable("PhanCong", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Finance.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhuongThuc")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.BaiThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeThiId")
                        .HasColumnType("uuid");

                    b.Property<float?>("DiemTracNghiem")
                        .HasColumnType("real");

                    b.Property<float?>("DiemTuLuan")
                        .HasColumnType("real");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NhanXet")
                        .HasColumnType("text");

                    b.Property<float?>("TongDiem")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeThiId");

                    b.HasIndex("HocVienId");

                    b.ToTable("BaiThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.BaiThiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaiThiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<string>("CauTraLoi")
                        .HasColumnType("text");

                    b.Property<float?>("Diem")
                        .HasColumnType("real");

                    b.Property<string>("NhanXet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaiThiId");

                    b.HasIndex("CauHoiId");

                    b.ToTable("BaiThiChiTiet", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("LopHocId");

                    b.ToTable("DangKy", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKyKhach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KetQua")
                        .HasColumnType("integer");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaiKhoanXuLyId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("TaiKhoanXuLyId");

                    b.ToTable("DangKyKhach", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("KyThiId")
                        .HasColumnType("uuid");

                    b.Property<int>("SoCauHoi")
                        .HasColumnType("integer");

                    b.Property<string>("TenDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KyThiId");

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThiCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeThiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DeThiId");

                    b.ToTable("DeThiCauHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KetQuaHocTap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("numeric");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KyThiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KyThiId");

                    b.ToTable("KetQuaHocTap", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KyThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("integer");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.ToTable("KyThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.NganHangDe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DapAnDung")
                        .HasColumnType("text");

                    b.Property<int>("LoaiCauHoi")
                        .HasColumnType("integer");

                    b.Property<int>("MucDo")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAmThanh")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NganHangDe", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.PhanHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("HocVienId");

                    b.ToTable("PhanHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DoiTuongNhan")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiGui")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NguoiGuiTaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiGuiTaiKhoanId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.NhatKyHeThong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("text");

                    b.Property<string>("DuLieuCu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DuLieuMoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.SaoLuuDuLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySaoLuu")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SaoLuuDuLieu", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KinhNghiem")
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrinhDo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoPhan")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GiaoVu", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.HocVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("HocVien", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("DatLaiMatKhauToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sdt")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThoiHanToken")
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<int>("VaiTro")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LichHoc", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.PhanCong", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Finance.ThanhToan", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany("ThanhToans")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.BaiThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DeThi", "DeThi")
                        .WithMany("BaiThis")
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany("BaiThis")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeThi");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.BaiThiChiTiet", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.BaiThi", "BaiThi")
                        .WithMany("BaiThiChiTiets")
                        .HasForeignKey("BaiThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DeThiCauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiThi");

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKy", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany("DangKys")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKyKhach", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoanXuLy")
                        .WithMany()
                        .HasForeignKey("TaiKhoanXuLyId");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoanXuLy");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.KyThi", "KyThi")
                        .WithMany("DeThis")
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyThi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThiCauHoi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.NganHangDe", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DeThi", "DeThi")
                        .WithMany("CauHois")
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KetQuaHocTap", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.KyThi", "KyThi")
                        .WithMany()
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KyThi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KyThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("KyThis")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.PhanHoi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.GiaoVien", "GiaoVien")
                        .WithMany("PhanHois")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany("PhanHois")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBao", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("ThongBaos")
                        .HasForeignKey("LopHocId");

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiGuiTaiKhoan")
                        .WithMany()
                        .HasForeignKey("NguoiGuiTaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiGuiTaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.NhatKyHeThong", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVien", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVu", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.HocVien", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("KyThis");

                    b.Navigation("LichHocs");

                    b.Navigation("PhanCongs");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.BaiThi", b =>
                {
                    b.Navigation("BaiThiChiTiets");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.Navigation("BaiThis");

                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KyThi", b =>
                {
                    b.Navigation("DeThis");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVien", b =>
                {
                    b.Navigation("PhanCongs");

                    b.Navigation("PhanHois");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.HocVien", b =>
                {
                    b.Navigation("BaiThis");

                    b.Navigation("DangKys");

                    b.Navigation("PhanHois");

                    b.Navigation("ThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
