// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsHuyenLC.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsHuyenLC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029103531_v9_UpdateKyThi")]
    partial class v9_UpdateKyThi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("numeric");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateOnly>("NgayKhaiGiang")
                        .HasColumnType("date");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LichHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CoHieuLuc")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("DenNgay")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhongHocId")
                        .HasColumnType("uuid");

                    b.Property<int>("Thu")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("PhongHocId");

                    b.ToTable("LichHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<int>("SiSoHienTai")
                        .HasColumnType("integer");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.PhanCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopHocId");

                    b.ToTable("PhanCong", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.PhongHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<int>("SoGhe")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Finance.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CongThanhToan")
                        .HasColumnType("text");

                    b.Property<Guid>("DangKyId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasColumnType("text");

                    b.Property<string>("MaThanhToan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayLap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NguoiCapNhatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiXacNhanId")
                        .HasColumnType("uuid");

                    b.Property<int>("PhuongThuc")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("numeric");

                    b.Property<string>("ThongTinNganHang")
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DangKyId");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiXacNhanId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.CauHoiDeThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeThiId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Diem")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("NhomCauHoiId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThuTuCauHoi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DeThiId");

                    b.HasIndex("NhomCauHoiId");

                    b.ToTable("CauHoiDeThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.CauTraLoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<string>("CauTraLoiText")
                        .HasColumnType("text");

                    b.Property<bool?>("Dung")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhienId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("PhienId");

                    b.ToTable("CauTraLoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayXepLop")
                        .HasColumnType("date");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("LopHocId");

                    b.ToTable("DangKy", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKyKhach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KetQua")
                        .HasColumnType("integer");

                    b.Property<Guid>("KhoaHocId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayXuLy")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaiKhoanXuLyId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("TaiKhoanXuLyId");

                    b.ToTable("DangKyKhach", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KyThiId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiDeThi")
                        .HasColumnType("integer");

                    b.Property<string>("MaDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiTaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("integer");

                    b.Property<int>("TongCauHoi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KyThiId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KetQuaHocTap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("numeric");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KyThiId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayThi")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KyThiId");

                    b.ToTable("KetQuaHocTap", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KyThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayThi")
                        .HasColumnType("date");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.ToTable("KyThi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.DapAnCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Dung")
                        .HasColumnType("boolean");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("text");

                    b.Property<string>("Nhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("DapAnCauHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapDo")
                        .HasColumnType("integer");

                    b.Property<int>("DoKho")
                        .HasColumnType("integer");

                    b.Property<string>("DoanVan")
                        .HasColumnType("text");

                    b.Property<int>("KyNang")
                        .HasColumnType("integer");

                    b.Property<int>("LoaiCauHoi")
                        .HasColumnType("integer");

                    b.Property<string>("LoiThoai")
                        .HasColumnType("text");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAmThanh")
                        .HasColumnType("text");

                    b.Property<string>("UrlHinhAnh")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NganHangCauHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapDo")
                        .HasColumnType("integer");

                    b.Property<int>("DoKho")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("SoLuongCauHoi")
                        .HasColumnType("integer");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAmThanh")
                        .HasColumnType("text");

                    b.Property<string>("UrlHinhAnh")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NhomCauHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHoiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NhomId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("NhomId");

                    b.ToTable("NhomCauHoiChiTiet", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.PhienLamBai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeThiId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("numeric");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NgayLam")
                        .HasColumnType("date");

                    b.Property<int?>("SoCauDung")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ThoiGianLam")
                        .HasColumnType("interval");

                    b.Property<int>("TongCauHoi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeThiId");

                    b.HasIndex("HocVienId");

                    b.ToTable("PhienLamBai", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.PhanHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HocVienId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoaiPhanHoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.ToTable("PhanHoi", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiGuiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NguoiGuiTaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiTaiKhoanId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBaoNguoiNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NguoiNhanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ThoiGianDoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThongBaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NguoiNhanId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("ThongBaoNguoiNhan", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.NhatKyHeThong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("text");

                    b.Property<string>("DuLieuCu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DuLieuMoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ThoiGian")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.SaoLuuDuLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NgaySaoLuu")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("SaoLuuDuLieu", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KinhNghiem")
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrinhDo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoPhan")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GiaoVu", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.HocVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("HocVien", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<int>("VaiTro")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LichHoc", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("PhongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.PhanCong", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Finance.ThanhToan", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DangKy", "DangKy")
                        .WithMany()
                        .HasForeignKey("DangKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId");

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId");

                    b.Navigation("DangKy");

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.CauHoiDeThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DeThi", "DeThi")
                        .WithMany("CacCauHoi")
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoi", null)
                        .WithMany("CacCauHoiDeThi")
                        .HasForeignKey("NhomCauHoiId");

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.CauTraLoi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.PhienLamBai", "Phien")
                        .WithMany()
                        .HasForeignKey("PhienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("Phien");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKy", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany("CacDangKy")
                        .HasForeignKey("LopHocId");

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DangKyKhach", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoanXuLy")
                        .WithMany()
                        .HasForeignKey("TaiKhoanXuLyId");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoanXuLy");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.KyThi", "KyThi")
                        .WithMany()
                        .HasForeignKey("KyThiId");

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyThi");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KetQuaHocTap", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.KyThi", "KyThi")
                        .WithMany()
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KyThi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.KyThi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Courses.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.DapAnCauHoi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", "CauHoi")
                        .WithMany("CacDapAn")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoiChiTiet", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", "CauHoi")
                        .WithMany("CacNhom")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoi", "Nhom")
                        .WithMany("CacChiTiet")
                        .HasForeignKey("NhomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.PhienLamBai", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.DeThi", "DeThi")
                        .WithMany()
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeThi");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.PhanHoi", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBao", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiGuiTaiKhoan")
                        .WithMany()
                        .HasForeignKey("NguoiGuiTaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiGuiTaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBaoNguoiNhan", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsHuyenLC.Domain.Entities.Learning.ThongBao", "ThongBao")
                        .WithMany("DanhSachNguoiNhan")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiNhan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.System.NhatKyHeThong", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVien", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.GiaoVu", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Users.HocVien", b =>
                {
                    b.HasOne("MsHuyenLC.Domain.Entities.Users.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Courses.LopHoc", b =>
                {
                    b.Navigation("CacDangKy");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.DeThi", b =>
                {
                    b.Navigation("CacCauHoi");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NganHangCauHoi", b =>
                {
                    b.Navigation("CacDapAn");

                    b.Navigation("CacNhom");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.OnlineExam.NhomCauHoi", b =>
                {
                    b.Navigation("CacCauHoiDeThi");

                    b.Navigation("CacChiTiet");
                });

            modelBuilder.Entity("MsHuyenLC.Domain.Entities.Learning.ThongBao", b =>
                {
                    b.Navigation("DanhSachNguoiNhan");
                });
#pragma warning restore 612, 618
        }
    }
}
