import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("layouts/Layout.tsx",[
    index("routes/trang-chu.tsx"),
    route("khoa-hoc", "routes/khoa-hoc.tsx"),
    route("luyen-thi", "routes/luyen-thi.tsx"),
    route("thi", "routes/thi.tsx"),
    route("ket-qua-thi", "routes/ket-qua-thi.tsx"),
    route("dashboard", "routes/dashboard.tsx"),
    route("dashboard-giao-vien", "routes/dashboard-giao-vien.tsx"),
    route("dang-nhap", "routes/dang-nhap.tsx"),
    route("doi-mat-khau", "routes/doi-mat-khau.tsx"),
    route("quen-mat-khau", "routes/quen-mat-khau.tsx"),
    route("dat-lai-mat-khau", "routes/dat-lai-mat-khau.tsx"),
    route("khoa-hoc-cua-toi", "routes/khoa-hoc-cua-toi.tsx"),
    route("thanh-toan/", "routes/thanh-toan.tsx"),
    route("lich-su-thanh-toan", "routes/lich-su-thanh-toan.tsx"),
    route("vnpay-return", "routes/vnpay-return.tsx"),
    route("phan-hoi", "routes/phan-hoi.tsx"),
  ]),
  route("admin", "routes/admin/_layout.tsx", [
    index("routes/admin/_index.tsx"),
    route("hoc-vien", "routes/admin/hoc-vien.tsx"),
    route("giao-vien", "routes/admin/giao-vien.tsx"),
    route("giao-vu", "routes/admin/giao-vu.tsx"),
    route("khoa-hoc", "routes/admin/khoa-hoc.tsx"),
    route("lop-hoc", "routes/admin/lop-hoc.tsx"),
    route("lich-hoc", "routes/admin/lich-hoc.tsx"),
    route("phong-hoc", "routes/admin/phong-hoc.tsx"),
    route("phan-cong", "routes/admin/phan-cong.tsx"),
    route("de-thi", "routes/admin/de-thi.tsx"),
    route("ky-thi", "routes/admin/ky-thi.tsx"),
    route("cau-hoi", "routes/admin/cau-hoi.tsx"),
    route("nhom-cau-hoi", "routes/admin/nhom-cau-hoi.tsx"),
    route("tai-khoan", "routes/admin/tai-khoan.tsx"),
    route("thong-bao", "routes/admin/thong-bao.tsx"),
    route("bao-cao-ket-qua", "routes/admin/bao-cao-ket-qua.tsx"),
    route("bao-cao-doanh-thu", "routes/admin/bao-cao-doanh-thu.tsx"),
    route("nhat-ky-he-thong", "routes/admin/nhat-ky-he-thong.tsx"),
    route("dang-ky", "routes/admin/dang-ky.tsx"),
    route("dang-ky-khach", "routes/admin/dang-ky-khach.tsx"),
    route("sao-luu-du-lieu", "routes/admin/sao-luu-du-lieu.tsx"),
    route("cai-dat", "routes/admin/cai-dat.tsx"),
  ]),
] satisfies RouteConfig;
